version: '3.5'
services:
    api:
        build:
            context: .
            dockerfile: 'Dockerfile.dev'
        ports:
            - '3000:3000'
        depends_on:
            - db-postgres
        restart: on-failure
    db-postgres:
        image: 'postgres:13-alpine'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        ports:
            - 5432
        restart: on-failure